import type {
  User,
  Course,
  Lesson,
  Enrollment,
  Certificate,
  Stats,
  TeacherStats,
  StudentStats,
} from "./types"

export const users: User[] = [
  {
    id: "1",
    name: "Admin Principal",
    email: "admin@edufy.com",
    role: "admin",
    avatar: "/avatars/admin.jpg",
    createdAt: "2024-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "María García",
    email: "maria@edufy.com",
    role: "profesor",
    avatar: "/avatars/maria.jpg",
    createdAt: "2024-02-10",
    status: "active",
  },
  {
    id: "3",
    name: "Carlos López",
    email: "carlos@edufy.com",
    role: "profesor",
    avatar: "/avatars/carlos.jpg",
    createdAt: "2024-02-15",
    status: "active",
  },
  {
    id: "4",
    name: "Ana Martínez",
    email: "ana@edufy.com",
    role: "estudiante",
    avatar: "/avatars/ana.jpg",
    createdAt: "2024-03-01",
    status: "active",
  },
  {
    id: "5",
    name: "Pedro Sánchez",
    email: "pedro@edufy.com",
    role: "estudiante",
    avatar: "/avatars/pedro.jpg",
    createdAt: "2024-03-05",
    status: "active",
  },
  {
    id: "6",
    name: "Laura Fernández",
    email: "laura@edufy.com",
    role: "estudiante",
    avatar: "/avatars/laura.jpg",
    createdAt: "2024-03-10",
    status: "inactive",
  },
]

export const courses: Course[] = [
  {
    id: "1",
    title: "Desarrollo Web con React",
    description:
      "Aprende a crear aplicaciones web modernas con React, hooks, y las mejores prácticas de desarrollo frontend.",
    thumbnail: "/courses/react.jpg",
    teacherId: "2",
    teacherName: "María García",
    category: "Desarrollo Web",
    price: 49.99,
    duration: "20 horas",
    level: "intermedio",
    rating: 4.8,
    studentsCount: 1250,
    lessonsCount: 45,
    status: "published",
    createdAt: "2024-02-20",
    updatedAt: "2024-04-01",
  },
  {
    id: "2",
    title: "Python para Ciencia de Datos",
    description:
      "Domina Python y sus bibliotecas para análisis de datos: Pandas, NumPy, y visualización con Matplotlib.",
    thumbnail: "/courses/python.jpg",
    teacherId: "3",
    teacherName: "Carlos López",
    category: "Ciencia de Datos",
    price: 59.99,
    duration: "25 horas",
    level: "principiante",
    rating: 4.9,
    studentsCount: 2100,
    lessonsCount: 52,
    status: "published",
    createdAt: "2024-02-25",
    updatedAt: "2024-04-05",
  },
  {
    id: "3",
    title: "Diseño UX/UI Profesional",
    description:
      "Aprende los fundamentos del diseño de experiencia de usuario y crea interfaces atractivas y funcionales.",
    thumbnail: "/courses/ux.jpg",
    teacherId: "2",
    teacherName: "María García",
    category: "Diseño",
    price: 44.99,
    duration: "18 horas",
    level: "principiante",
    rating: 4.7,
    studentsCount: 890,
    lessonsCount: 38,
    status: "published",
    createdAt: "2024-03-01",
    updatedAt: "2024-04-10",
  },
  {
    id: "4",
    title: "Machine Learning Avanzado",
    description:
      "Profundiza en algoritmos de machine learning, redes neuronales y deep learning con TensorFlow.",
    thumbnail: "/courses/ml.jpg",
    teacherId: "3",
    teacherName: "Carlos López",
    category: "Inteligencia Artificial",
    price: 79.99,
    duration: "35 horas",
    level: "avanzado",
    rating: 4.9,
    studentsCount: 650,
    lessonsCount: 68,
    status: "published",
    createdAt: "2024-03-10",
    updatedAt: "2024-04-12",
  },
  {
    id: "5",
    title: "JavaScript Moderno ES6+",
    description:
      "Domina las características modernas de JavaScript y conviértete en un desarrollador frontend experto.",
    thumbnail: "/courses/js.jpg",
    teacherId: "2",
    teacherName: "María García",
    category: "Desarrollo Web",
    price: 39.99,
    duration: "15 horas",
    level: "principiante",
    rating: 4.6,
    studentsCount: 1800,
    lessonsCount: 35,
    status: "published",
    createdAt: "2024-03-15",
    updatedAt: "2024-04-15",
  },
  {
    id: "6",
    title: "Base de Datos con PostgreSQL",
    description:
      "Aprende a diseñar, implementar y optimizar bases de datos relacionales con PostgreSQL.",
    thumbnail: "/courses/sql.jpg",
    teacherId: "3",
    teacherName: "Carlos López",
    category: "Base de Datos",
    price: 54.99,
    duration: "22 horas",
    level: "intermedio",
    rating: 4.7,
    studentsCount: 720,
    lessonsCount: 42,
    status: "published",
    createdAt: "2024-03-20",
    updatedAt: "2024-04-18",
  },
]

export const lessons: Lesson[] = [
  {
    id: "1",
    courseId: "1",
    title: "Introducción a React",
    description: "Conoce los fundamentos de React y su ecosistema",
    videoUrl: "https://example.com/video1",
    duration: "15:30",
    order: 1,
  },
  {
    id: "2",
    courseId: "1",
    title: "Componentes y Props",
    description: "Aprende a crear componentes reutilizables",
    videoUrl: "https://example.com/video2",
    duration: "22:45",
    order: 2,
  },
  {
    id: "3",
    courseId: "1",
    title: "Estado y Hooks",
    description: "Manejo del estado con useState y useEffect",
    videoUrl: "https://example.com/video3",
    duration: "28:15",
    order: 3,
  },
  {
    id: "4",
    courseId: "1",
    title: "Context API",
    description: "Gestión de estado global sin librerías externas",
    videoUrl: "https://example.com/video4",
    duration: "25:00",
    order: 4,
  },
  {
    id: "5",
    courseId: "1",
    title: "React Router",
    description: "Navegación en aplicaciones SPA",
    videoUrl: "https://example.com/video5",
    duration: "20:30",
    order: 5,
  },
  {
    id: "6",
    courseId: "2",
    title: "Introducción a Python",
    description: "Primeros pasos con Python",
    videoUrl: "https://example.com/video6",
    duration: "18:00",
    order: 1,
  },
  {
    id: "7",
    courseId: "2",
    title: "NumPy Básico",
    description: "Arrays y operaciones numéricas",
    videoUrl: "https://example.com/video7",
    duration: "30:00",
    order: 2,
  },
  {
    id: "8",
    courseId: "2",
    title: "Pandas para Análisis",
    description: "DataFrames y manipulación de datos",
    videoUrl: "https://example.com/video8",
    duration: "35:00",
    order: 3,
  },
]

export const enrollments: Enrollment[] = [
  {
    id: "1",
    userId: "4",
    courseId: "1",
    progress: 65,
    enrolledAt: "2024-03-15",
    lastAccessedAt: "2024-04-20",
  },
  {
    id: "2",
    userId: "4",
    courseId: "2",
    progress: 40,
    enrolledAt: "2024-03-20",
    lastAccessedAt: "2024-04-19",
  },
  {
    id: "3",
    userId: "5",
    courseId: "1",
    progress: 100,
    enrolledAt: "2024-03-10",
    completedAt: "2024-04-15",
    lastAccessedAt: "2024-04-15",
  },
  {
    id: "4",
    userId: "5",
    courseId: "3",
    progress: 25,
    enrolledAt: "2024-04-01",
    lastAccessedAt: "2024-04-18",
  },
  {
    id: "5",
    userId: "6",
    courseId: "2",
    progress: 80,
    enrolledAt: "2024-03-25",
    lastAccessedAt: "2024-04-17",
  },
]

export const certificates: Certificate[] = [
  {
    id: "1",
    userId: "5",
    courseId: "1",
    courseName: "Desarrollo Web con React",
    issuedAt: "2024-04-15",
    certificateUrl: "/certificates/cert1.pdf",
  },
]

export const adminStats: Stats = {
  totalUsers: 4850,
  totalCourses: 156,
  totalEnrollments: 12500,
  revenue: 485000,
  activeStudents: 3200,
  completionRate: 68,
}

export const teacherStats: TeacherStats = {
  totalStudents: 4140,
  totalCourses: 3,
  totalRevenue: 125000,
  averageRating: 4.73,
  completionRate: 72,
}

export const studentStats: StudentStats = {
  enrolledCourses: 4,
  completedCourses: 1,
  hoursLearned: 45,
  certificates: 1,
  currentStreak: 12,
}

export const categories = [
  "Desarrollo Web",
  "Ciencia de Datos",
  "Diseño",
  "Inteligencia Artificial",
  "Base de Datos",
  "Marketing Digital",
  "Negocios",
  "Idiomas",
]

export const monthlyRevenueData = [
  { month: "Ene", revenue: 32000, students: 280 },
  { month: "Feb", revenue: 38000, students: 320 },
  { month: "Mar", revenue: 45000, students: 410 },
  { month: "Abr", revenue: 52000, students: 480 },
  { month: "May", revenue: 48000, students: 450 },
  { month: "Jun", revenue: 55000, students: 520 },
]

export const courseEnrollmentData = [
  { name: "React", value: 1250 },
  { name: "Python", value: 2100 },
  { name: "UX/UI", value: 890 },
  { name: "ML", value: 650 },
  { name: "JavaScript", value: 1800 },
]
